server:
    context-path: /api-manager


datasource:
    password: sql123
    username: root

quartz:
  enabled: true

job:
  frequency: 3000

jdbc:
    driver:
        className: com.mysql.jdbc.Driver

properties:
    hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        hbm2ddl:
            auto: update
        id:
            new_generator_mappings: false
        show_sql: true
        transaction:
            auto_close_session: true
spring:
    jackson:
        serialization:
            INDENT_OUTPUT: true
    profiles:
      active: dev-ceuma
    datasource:
      url: jdbc:h2:mem:test
      username: sa
      password:
      driver-class-name: org.h2.Driver